services:
  app:
    image: ghcr.io/irsyamokta/portfolio:latest
    build:
      context: .
      args:
        - VITE_TURNSTILE_SITE_KEY=${VITE_TURNSTILE_SITE_KEY}
    container_name: portfolio
    restart: unless-stopped
    ports:
      - "3005:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      HOST: 0.0.0.0
      VITE_TURNSTILE_SITE_KEY: ${VITE_TURNSTILE_SITE_KEY}
    networks:
      - odoonet

networks:
  odoonet:
    external: true